### ISSUE TITLE
Back button closes mini player and stops the song

### ISSUE THREAD

**Issue by fessmm** [khaled-0/Syncara#24]
Like the title says. It stops the music while in the app. It should close the app without stopping the music. 

Edit: while you browse in the "more" tab and sometimes also in the library tab

**Comment by khaled-0** [comment]
Actually no. It's the correct behaviour. If you want to close the app without closing music. Press the home button. 
Making the back button act like the home button is wrong ux imo.
I often press the back button repeatedly to close everything

**Comment by fessmm** [comment]
Hm i see
