### ISSUE TITLE
"Sleep Timer" button duplicated

### ISSUE THREAD

**Issue by sehrschlechtYT** [khaled-0/Syncara#26]
Not sure if this intended, but there are two *Sleep Timer* buttons:

![image](https://github.com/user-attachments/assets/471d9ba8-8009-4020-8c6c-d02e762d79af)

The code to create the button seems to exist twice: https://github.com/khaled-0/Syncara/blob/d2ee8e5dc3346dfd8621e6cc8b6ee08d22dc7fd6/lib/app/player/player_menu_sheet.dart#L17-L34

(using the Flathub app)

**Comment by khaled-0** [comment]
yes I saw that, I was working on Playback speed on a separate branch and it is leftover code from there.
Will be fixed on nightly & next release.

**Comment by sehrschlechtYT** [comment]
> yes I saw that, I was working on Playback speed on a separate branch and it is leftover code from there.
> Will be fixed on nightly & next release.

Awesome, thank you!
