### ISSUE TITLE
Feature Request: Play playlists in reverse order

### ISSUE THREAD

**Issue by sehrschlechtYT** [khaled-0/Syncara#27]
This is an essential feature which the official YT Music frontend is missing. I always like to listen to the songs I added most recently into my playlists and therefore am currently using https://playlist.tools/ to achieve this.

It would be cool to have this in Syncara, and this feature would offer a benefit for users over the official YT Music.

**Comment by khaled-0** [comment]
Did you know you can sort your playlists on YouTube 
in your case **Date Added(newest)** (look screenshot)
and the order will be synced by Syncara.

But I will add an option to sort the currently playing queue only without modifying the playlist permanently.

![Screenshot_2024-12-26-08-59-09-334_app revanced android youtube](https://github.com/user-attachments/assets/8e99593a-6924-4b6a-b860-f3c3d1751408)

**Comment by sehrschlechtYT** [comment]
> Did you know you can sort your playlists on YouTube 
> in your case **Date Added(newest)** (look screenshot)
> and the order will be synced by Syncara.
> 
> But I will add an option to sort the currently playing queue only without modifying the playlist permanently.
> 
> ![Screenshot_2024-12-26-08-59-09-334_app revanced android youtube](https://github.com/user-attachments/assets/8e99593a-6924-4b6a-b860-f3c3d1751408)
> 

Nice! Not sure why this feature is a thing in YouTube but not in YT Music where it would actually be more useful

**Comment by khaled-0** [comment]
![image](https://github.com/user-attachments/assets/af6f9c19-fdad-4810-bee4-539b80acf69d)
